### ISSUE TITLE
Is it feasible to run this program with python3?

### ISSUE THREAD

**Issue by Shame-fight** [kumuji/trt_yolo_ros#6]
Hi~ I want to run this program on jetson nano: At present, my environment is based on[https://github.com/jkjung-avt/tensorrt_demos](url), can I use your code without changing the environment, that is, run under python3. If possible, I will start immediately~

**Comment by kumuji** [comment]
Should be possible. If you will have any problem, it is in my interest to fix it as fast as possible.

But, please be sure that your ROS also uses python3.
